# Generated by Django 3.0.3 on 2020-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_home_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='value',
            new_name='first_value',
        ),
        migrations.AddField(
            model_name='price',
            name='second_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='third_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
