# Generated by Django 3.0.3 on 2020-04-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='email',
            new_name='home_email',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='core.Home'),
        ),
    ]
