# Generated by Django 3.0.3 on 2020-04-16 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200414_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='card_cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='card_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_name', to='core.Home'),
        ),
    ]
