# Generated by Django 3.0.3 on 2020-03-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_email', to='registration.Registration')),
                ('login_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_password', to='registration.Registration')),
            ],
        ),
    ]
